version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - apt-get update -y
      - apt-get install -y docker.io
      - curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '(?<="tag_name": ")([^"]+)')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building Docker image...
      - docker-compose -f docker-compose.yml build
  post_build:
    commands:
      - echo Build completed successfully
